name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Install dependencies (castle company)
        working-directory: castle-company
        run: |
          npm install

      - name: Running tests (castle company)
        working-directory: castle-company
        run: |
          npm run test

      - name: Install dependencies (transformation company)
        working-directory: transformation-company
        run: |
          npm install

      - name: Running tests (transformation company)
        working-directory: transformation-company
        run: |
          npm run test:ci

